import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from './componentes/Footer';
import NavBar from './componentes/NavBar';
import 'mdb-react-ui-kit/dist/css/mdb.min.css'
import "@fortawesome/fontawesome-free/css/all.min.css"
import styled from 'styled-components'

export const metadata = {
  title: 'StringElements Blog',
  description: 'Generated by create next app',
}

const handleMessageCallback = (msg) => {
  if (msg.tipo !== 'nada') {
      let icon = '';
      if (msg.tipo === 'sucesso')
          icon = 'success';
      else if (msg.tipo === 'erro')
          icon = 'error';

      MySwal.fire({
          position: 'top-end',
          icon: icon,
          title: msg.texto,
          showConfirmButton: false,
          timer: 3500,
          toast: true
      })
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar modo="semLogin"/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
